_target_: src.models.eps_ibp_module.EpsIBP

net:
  _target_: src.models.components.dm_models.cnn_7layer_bn_imagenet
  input_ch: 3
  input_dim: 64

# Params for computing bounds in BoundedModule
input_shape: [3, 64, 64]
num_classes: 200
data_mean: ${datamodule.data_mean}
data_std: ${datamodule.data_std}
bound_norm: .inf
bound_method: IBP

eps_test: [0.00392156863]    # 1/255

max_eps: 0.00392156863 # 1/255
xtol: 1.e-8
rtol: 1.e-5
maxiter: 100
ftol: 1.e-8

# Loss function params
standard_loss: CrossEntropy
standard_label_smoothing: 0.0
robust_loss: CrossEntropy
robust_label_smoothing: 0.0

# Optimzer and LR scheduler
optimizer: 
  name: Adam
  amsgrad: false
  lr: 0.001
  weight_decay: 0.0

init_method: "ibp"
