# https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.ModelSummary.html

# Generates a summary of all layers in a LightningModule.
# Look at the above link for more detailed information.
model_summary:
  _target_: pytorch_lightning.callbacks.ModelSummary
  max_depth: 2 # the maximum depth of layer nesting that the summary will include
